processor_cfg: 
  name: '.processor.pseudo.train'
  optimizer: null
  model_cfg: 
    name: '.models.pseudo.model'
    in_channels: 3
    out_channels: 60
    weight: null
  dataset_cfg: 
    name: '.datasets.pseudo.dataset'
    data_path: null