argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus


processor_cfg:
  name: '.processor.image2skeleton.inference'
  dataset_cfg:
    video_file: $ Path of Your Video Path

  detection_cfg:
    model_cfg: $ Path for Your Config of Detection Model in MMDetection
    checkpoint_file:  $ Path for the CheckPoint of Upper Detection Model in MMDetection
    bbox_thre: 0.8
  skeleton_cfg:
    model_cfg: 'configs/estimation/hrnet/pose_hrnet_w32_256x192_test.yaml'
    checkpint_file: 'checkpoints/pose_hrnet_w32_256x192_official.pth'
    data_cfg:
      image_size:
        - 192
        - 256
      pixel_std: 200
      image_mean:
        - 0.485
        - 0.456
        - 0.406
      image_std:
        - 0.229
        - 0.224
        - 0.225
      post_process: true
      save_image : true
      save_dir: 'save/'

  gpus: 4

