argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from

processor_cfg:
  name: "processor.recognition.test"
  workers: 16
  checkpoint:

  # model setting
  model_cfg:
    name: "models.backbones.ST_GCN"
    in_channels: 3
    num_class: 3
    edge_importance_weighting: True
    graph_cfg:
      layout: "coco"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    name: "datasets.recognition.SkeletonDataset"
    data_dir: ./data/dataset_example
    data_subscripts: cvtm->ctvm

  # dataloader setting
  batch_size: 3
  gpus: 1
