argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: ./work_dir/recognition/st_gcn/kinetics-skeleton-from-openpose.norm/latest.pth

processor_cfg:
  type: "processor.recognition.test"
  checkpoint:
  workers: 32

  # model setting
  model_cfg:
    type: "models.backbones.ST_GCN_18"
    in_channels: 3
    num_class: 400
    edge_importance_weighting: True
    data_bn: False
    graph_cfg:
      layout: "openpose"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: "datasets.DataPipeline"
    data_source:
      type: "datasets.SkeletonLoader"
      data_dir: ./data/Kinetics/skeleton-from-openpose/val2014
      num_track: 2
    pipeline:
      - {type: "datasets.skeleton.normalize_with_mask", mean: [176, 122, 0.46], std: [58, 46, 0.21], mask_channel: 2}
      - {type: "datasets.skeleton.pad_zero", size: 300}
      - {type: "datasets.skeleton.random_crop", size: 300}
      - {type: "datasets.skeleton.transpose", order: [0, 2, 1, 3]}
      - {type: "datasets.skeleton.to_tuple"}

  # dataloader setting
  batch_size: 256
  gpus: 4
