argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  video:
    bind_to: processor_cfg.dataset_cfg.video_file
    help: path to input video

processor_cfg:
  name: ".processor.image2skeleton.inference"
  dataset_cfg:
    video_file: resource/media/skateboarding.mp4

  detection_cfg:
    model_cfg: configs/mmdet/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py
    checkpoint_file: checkpoints/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e_20190408-0e50669c.pth
    bbox_thre: 0.8
  skeleton_cfg:
    model_cfg: configs/pose_estimation/hrnet/pose_hrnet_w32_256x192_test.yaml
    checkpoint_file: checkpoints/pose_hrnet_w32_256x192_official.pth
    data_cfg:
      image_size:
        - 192
        - 256
      pixel_std: 200
      image_mean:
        - 0.485
        - 0.456
        - 0.406
      image_std:
        - 0.229
        - 0.224
        - 0.225
      post_process: true
      save_video: true
      save_dir: "work_dir/pose_estimation_demo"

  gpus: 8
