processor_cfg:
  name: ".processor.pose_demo.inference"
  gpus: 1
  worker_per_gpu: 1
  video_file: resource/media/skateboarding.mp4

  detection_cfg:
    model_cfg: configs/mmdet/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py
    checkpoint_file: mmskeleton://mmdet/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e
    bbox_thre: 0.8
  skeleton_cfg:
    model_cfg: configs/pose_estimation/hrnet/pose_hrnet_w32_256x192_test.yaml
    checkpoint_file: mmskeleton://pose_estimation/pose_hrnet_w32_256x192
    data_cfg:
      image_size:
        - 192
        - 256
      pixel_std: 200
      image_mean:
        - 0.485
        - 0.456
        - 0.406
      image_std:
        - 0.229
        - 0.224
        - 0.225
      post_process: true
  save_dir: "work_dir/pose_demo_HD"

argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  video:
    bind_to: processor_cfg.video_file
    help: path to input video
  worker_per_gpu:
    bind_to: processor_cfg.worker_per_gpu
    help: number of workers for each gpu
  skeleton_model:
    bind_to: processor_cfg.skeleton_cfg.model_cfg
  skeleton_checkpoint:
    bind_to: processor_cfg.skeleton_cfg.checkpoint_file
  detection_model:
    bind_to: processor_cfg.detection_cfg.model_cfg
  detection_checkpoint:
    bind_to: processor_cfg.detection_cfg.checkpoint_file
