work_dir: ./work_dir/Kinetics/TCN

# feeder
feeder: st_gcn.feeder.Feeder_kinetics
train_feeder_args:
  mode: train
  random_choose: True
  random_move: True
  window_size: 300 
  num_person: 1
  data_path: ./data/kinetics-skeleton/kinetics_train
  label_path : ./data/kinetics-skeleton/kinetics_train_label.json
test_feeder_args:
  mode: test 
  num_person: 1
  data_path: ./data/kinetics-skeleton/kinetics_val
  label_path : ./data/kinetics-skeleton/kinetics_val_label.json


# model
model: st_gcn.net.TCN
model_args:
  num_class: 400
  channel: 54 
  window_size: 300
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 70]

# training
device: 0  
batch_size: 512 
test_batch_size: 512 
num_epoch: 80
nesterov: True


