processor_cfg: 
  name: '.processor.recognizer.train'

  # model setting
  model_cfg: 
    name: '.models.backbones.ST_GCN'
    in_channels: 3
    num_class: 60
    dropout: 0.5
    edge_importance_weighting: True
    graph_cfg:
      layout: 'ntu-rgb+d'
      strategy: 'spatial'

  # dataset setting
  dataset_cfg: 
    name: '.datasets.SkeletonFeeder'
    data_path: ./data/NTU-RGB-D/xview/train_data.npy
    label_path: ./data/NTU-RGB-D/xview/train_label.pkl
  
  # dataloader setting
  batch_size: 64 

  # optimizer setting
  optimizer_cfg:
    name: 'torch.optim.SGD'
    lr: 0.1
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0001

  # runner setting
  work_dir: work_dir/tmp
  log_level: 0
  lr_config:
    policy: 'step'
    step: [10, 50]
  total_epochs: 80
  gpus: 4

  # device: [0,1,2,3]
  # test_batch_size: 64