processor_cfg: 
  name: '.processor.pseudo.train'
  optimizer: null

  # model setting
  model_cfg: 
    name: '.models.backbones.ST_GCN'
    in_channels: 3
    num_class: 60
    dropout: 0.5
    edge_importance_weighting: True
    graph_cfg:
      layout: 'ntu-rgb+d'
      strategy: 'spatial'

  # dataset setting
  dataset_cfg: 
    name: '.datasets.pseudo.dataset'
    data_path: null